kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 22
    hostPort: 22
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  extraMounts:
  - hostPath: /c/Users/Max/onedrive/desktop/mysql
    containerPath: /c/mysql
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
- role: worker
  extraMounts:
  - hostPath: /c/Users/Max/onedrive/desktop/mysql
    containerPath: /c/mysql
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
- role: worker
  extraMounts:
  - hostPath: /c/Users/Max/onedrive/desktop/mysql
    containerPath: /c/mysql
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
- role: worker
  extraMounts:
  - hostPath: /c/Users/Max/onedrive/desktop/mysql
    containerPath: /c/mysql
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
